# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
setup_travis

default_platform(:ios)

platform :ios do

  desc "Run all application tests (ui/unit)"
  lane :tests do |options|
     if options[:screenshots]
       screenshots
       unit_tests
     else
       ui_tests
       unit_tests
     end
  end

  desc "App Store deployment"
  lane :release do
    build_app(scheme: "ChuckNorrisFacts",
              workspace: "ChuckNorrisFacts.xcworkspace",
     	      include_bitcode: true)
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "ChuckNorrisFacts.xcworkspace",
                        scheme: "ChuckNorrisFacts")
  end

  desc "Run application ui tests"
  lane :ui_tests do
    run_tests(scheme: "ChuckNorrisFactsUITests",
              devices: ["iPhone 12 Pro Max"])
  end

  desc "Run application unit tests"
  lane :unit_tests do
    run_tests(scheme: "ChuckNorrisFactsTests",
              devices: ["iPhone 12 Pro Max"])
  end
end
