# platform :ios, '9.0'

target 'ChuckNorrisFacts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChuckNorrisFacts
  pod 'RxSwift', '6.0.0-rc.2'
  pod 'RxCocoa', '6.0.0-rc.2'

  target 'ChuckNorrisFactsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.0.0-rc.2'
    pod 'RxTest', '6.0.0-rc.2'
    pod 'iOSSnapshotTestCase'
  end

  target 'ChuckNorrisFactsUITests' do
    # Pods for testing
  end

end
